import { GoogleGenAI, Modality, Chat, GenerateContentResponse } from "@google/genai";

const API_KEY = process.env.API_KEY;
if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

// Helper to convert data URL to a Gemini Part object
const dataUrlToGenerativePart = (dataUrl: string) => {
  const [meta, base64Data] = dataUrl.split(',');
  const mimeType = meta.split(';')[0].split(':')[1];
  return {
    inlineData: {
      mimeType,
      data: base64Data,
    },
  };
};

export const geminiService = {
  editImage: async (imageDataUrl: string, prompt: string, maskDataUrl?: string): Promise<string> => {
    try {
      const imagePart = dataUrlToGenerativePart(imageDataUrl);
      
      const parts: any[] = [imagePart];
      let finalPrompt = prompt;

      if (maskDataUrl) {
        const maskPart = dataUrlToGenerativePart(maskDataUrl);
        parts.push(maskPart);
        finalPrompt = `${prompt}. IMPORTANT: Apply this change ONLY to the area marked in white on the provided mask image. The rest of the image must remain untouched.`;
      }
      
      parts.push({ text: finalPrompt });

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: { parts },
        config: {
          responseModalities: [Modality.IMAGE],
        },
      });

      const candidate = response.candidates?.[0];
      if (candidate?.content?.parts) {
          for (const part of candidate.content.parts) {
              if (part.inlineData) {
                  const { mimeType, data } = part.inlineData;
                  return `data:${mimeType};base64,${data}`;
              }
          }
      }
      
      throw new Error("No image was generated by the model.");
    } catch (error) {
      console.error("Error editing image:", error);
      throw new Error("Failed to edit the image. Please try again.");
    }
  },

  generateImage: async (prompt: string): Promise<string> => {
    try {
        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: prompt,
            config: {
              numberOfImages: 1,
              outputMimeType: 'image/png',
              aspectRatio: '16:9',
            },
        });

        const generatedImage = response.generatedImages[0];
        if (generatedImage && generatedImage.image.imageBytes) {
            const base64ImageBytes = generatedImage.image.imageBytes;
            return `data:image/png;base64,${base64ImageBytes}`;
        }
        throw new Error("No image was generated by the model.");
    } catch(error) {
        console.error("Error generating image:", error);
        throw new Error("Failed to generate the image. Please try again.");
    }
  },

  startChat: (systemInstruction?: string): Chat => {
    return ai.chats.create({
      model: 'gemini-2.5-flash',
      config: {
        systemInstruction: systemInstruction || 'You are a helpful and friendly chatbot. You can answer questions, provide information, and engage in conversation.',
      }
    });
  },
  
  sendMessage: async (chat: Chat, message: string): Promise<GenerateContentResponse> => {
      return await chat.sendMessage({ message });
  }
};